Logging:
  LogLevel:
    Default: Information
    Microsoft: Warning

Flux:
  Sources:
    - Type: "Udp"
      Port: 5140
  Processors:
    - Name: "Enrichment"
  Sinks:
    - Type: File
      Path: logs/output.csv
